export const menu = [
  {
    id: "chai",
    title: "Chai",
    icon: "Coffee",
    items: [
      { name: "Modi Ji Ki Chai"},
      { name: "Kulhad Chai"},
      { name: "Honey Lemon Tea"},
      { name: "Ginger Honey Lemon Tea" },
    ],
  },
  {
    id: "mocktails",
    title: "Mocktails",
    icon: "Wine",
    items: [
      { name: "Nimbu Pani"},
      { name: "Lemonade (Soda)"},
      { name: "Virgin Mojito"},
      { name: "Mint Mojito" },
      { name: "Kiwi Cooler Mojito"},
      { name: "Blue Lagoon"},
      { name: "Orange Mojito"},
      { name: "Watermelon Punch"},
      { name: "Blue Berry Mojito"},
      { name: "Black Currant Mojito" },
      { name: "Strawberry Mojito"},
      { name: "Green Apple Mojito"},
      { name: "Pineapple Mojito" },
      { name: "Cranberry Mojito"},
    ],
  },
  {
    id: "frappes",
    title: "Frappes",
    icon: "CupSoda",
    items: [
      { name: "Frappe (Cold Coffee)"},
      { name: "Hazelnut Frappe"},
      { name: "Caramel Frappe"},
      { name: "Irish Frappe"},
      { name: "Dark Frappe"},
      { name: "Choco Frappe" },
      { name: "Double Choco Chip Frappe" },
      { name: "Oreo Frappe" },
    ],
  },
  {
    id: "shakes",
    title: "Shakes",
    icon: "Milk",
    items: [
      { name: "Black Currant Shake"},
      { name: "Strawberry Shake"},
      { name: "Butter Scotch Shake" },
      { name: "Mango Shake"},
      { name: "Blue Berry Shake"},
      { name: "Vanilla Shake"},
      { name: "Chocolate Shake"},
      { name: "Oreo Shake"},
      { name: "KitKat Shake"},
      { name: "Biscoff Shake"},
      { name: "Nutella Shake"},
    ],
  },
  {
    id: "fries",
    title: "Fries",
    icon: "Drumstick",
    items: [
      { name: "Salted Fries" },
      { name: "Peri Peri Fries"},
      { name: "Cheese Fries"},
    ],
  },
  {
    id: "maggi",
    title: "Maggi",
    icon: "Soup",
    items: [
      { name: "Plain Maggi"},
      { name: "Peri Peri Maggi"},
      { name: "Veg Masala Maggi" },
      { name: "Tandoori Maggi" },
      { name: "Cheese Maggi"},
      { name: "Punjabi Tadka Maggi"},
      { name: "Baked Tandoori Maggi"},
    ],
  },
  {
    id: "pizza",
    title: "Pizza",
    icon: "Pizza",
    items: [
      { name: "Margherita Pizza"},
      { name: "OTC Pizza"},
      { name: "Corn & Onion Pizza"},
      { name: "Chilly Paneer Pizza"},
      { name: "Cheese Burst Pizza" },
      { name: "Tandoori Paneer Pizza"},
      { name: "Farm Pizza"},
      { name: "Italian Pizza"},
      { name: "Mushroom Cheese Pizza"},
      { name: "Modi Ji Special Pizza" },
    ],
  },
  {
    id: "sandwiches",
    title: "Sandwiches",
    icon: "Sandwich",
    items: [
      { name: "Bombay Sandwich"},
      { name: "Veg Grill Sandwich"},
      { name: "Cheese Grill Sandwich"},
      { name: "Paneer Tadka Sandwich"},
      { name: "Cheese Corn Sandwich"},
      { name: "Modi Ji Special Sandwich"},
      { name: "Double Layer Baked Sandwich"},
    ],
  },
  {
    id: "burgers",
    title: "Burgers",
    icon: "Beef",
    items: [
      { name: "Aloo Tikki Burger" },
      { name: "Spicy Tandoori Burger"},
      { name: "Paneer Loaded Burger" },
      { name: "Classic Cheese Burger"},
      { name: "Double Tikki Burger"},
    ],
  },
];