export const menu = [
  {
    id: "chai",
    title: "Chai",
    icon: "Coffee",
    items: [
      { name: "Modi Ji Ki Chai", price: 40 },
      { name: "Kulhad Chai", price: 45 },
      { name: "Honey Lemon Tea", price: 75 },
      { name: "Ginger Honey Lemon Tea", price: 79 },
    ],
  },
  {
    id: "mocktails",
    title: "Mocktails",
    icon: "Wine",
    items: [
      { name: "Nimbu Pani", price: 89 },
      { name: "Lemonade (Soda)", price: 99 },
      { name: "Virgin Mojito", price: 119 },
      { name: "Mint Mojito", price: 119 },
      { name: "Kiwi Cooler Mojito", price: 129 },
      { name: "Blue Lagoon", price: 129 },
      { name: "Orange Mojito", price: 129 },
      { name: "Watermelon Punch", price: 129 },
      { name: "Blue Berry Mojito", price: 129 },
      { name: "Black Currant Mojito", price: 129 },
      { name: "Strawberry Mojito", price: 129 },
      { name: "Green Apple Mojito", price: 129 },
      { name: "Pineapple Mojito", price: 129 },
      { name: "Cranberry Mojito", price: 129 },
    ],
  },
  {
    id: "frappes",
    title: "Frappes",
    icon: "CupSoda",
    items: [
      { name: "Frappe (Cold Coffee)", price: 139 },
      { name: "Hazelnut Frappe", price: 159 },
      { name: "Caramel Frappe", price: 159 },
      { name: "Irish Frappe", price: 159 },
      { name: "Dark Frappe", price: 159 },
      { name: "Choco Frappe", price: 159 },
      { name: "Double Choco Chip Frappe", price: 169 },
      { name: "Oreo Frappe", price: 179 },
    ],
  },
  {
    id: "shakes",
    title: "Shakes",
    icon: "Milk",
    items: [
      { name: "Black Currant Shake", price: 139 },
      { name: "Strawberry Shake", price: 139 },
      { name: "Butter Scotch Shake", price: 139 },
      { name: "Mango Shake", price: 139 },
      { name: "Blue Berry Shake", price: 139 },
      { name: "Vanilla Shake", price: 149 },
      { name: "Chocolate Shake", price: 149 },
      { name: "Oreo Shake", price: 159 },
      { name: "KitKat Shake", price: 169 },
      { name: "Biscoff Shake", price: 209 },
      { name: "Nutella Shake", price: 209 },
    ],
  },
  {
    id: "fries",
    title: "Fries",
    icon: "Drumstick",
    items: [
      { name: "Salted Fries", price: 120 },
      { name: "Peri Peri Fries", price: 130 },
      { name: "Cheese Fries", price: 150 },
    ],
  },
  {
    id: "maggi",
    title: "Maggi",
    icon: "Soup",
    items: [
      { name: "Plain Maggi", price: 100 },
      { name: "Peri Peri Maggi", price: 120 },
      { name: "Veg Masala Maggi", price: 120 },
      { name: "Tandoori Maggi", price: 140 },
      { name: "Cheese Maggi", price: 160 },
      { name: "Punjabi Tadka Maggi", price: 170 },
      { name: "Baked Tandoori Maggi", price: 180 },
    ],
  },
  {
    id: "pizza",
    title: "Pizza",
    icon: "Pizza",
    items: [
      { name: "Margherita Pizza", price: 180 },
      { name: "OTC Pizza", price: 199 },
      { name: "Corn & Onion Pizza", price: 210 },
      { name: "Chilly Paneer Pizza", price: 230 },
      { name: "Cheese Burst Pizza", price: 230 },
      { name: "Tandoori Paneer Pizza", price: 240 },
      { name: "Farm Pizza", price: 250 },
      { name: "Italian Pizza", price: 270 },
      { name: "Mushroom Cheese Pizza", price: 270 },
      { name: "Modi Ji Special Pizza", price: 280 },
    ],
  },
  {
    id: "sandwiches",
    title: "Sandwiches",
    icon: "Sandwich",
    items: [
      { name: "Bombay Sandwich", price: 109 },
      { name: "Veg Grill Sandwich", price: 129 },
      { name: "Cheese Grill Sandwich", price: 139 },
      { name: "Paneer Tadka Sandwich", price: 159 },
      { name: "Cheese Corn Sandwich", price: 159 },
      { name: "Modi Ji Special Sandwich", price: 179 },
      { name: "Double Layer Baked Sandwich", price: 179 },
    ],
  },
  {
    id: "burgers",
    title: "Burgers",
    icon: "Beef",
    items: [
      { name: "Aloo Tikki Burger", price: 99 },
      { name: "Spicy Tandoori Burger", price: 119 },
      { name: "Paneer Loaded Burger", price: 119 },
      { name: "Classic Cheese Burger", price: 139 },
      { name: "Double Tikki Burger", price: 149 },
    ],
  },
];